name: flutter_app_environment
description: Simple solution to handle environment variables using `.json` or
  config in entrypoint file.
version: 2.0.0
homepage: https://github.com/alexeynobody/flutter-app-environment

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
